# Generated by Django 3.1 on 2020-08-21 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='origin',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
